name=dtu
version=1.0
author=ExploreEmbedded.com
maintainer=ExploreEmbedded.com
sentence= dtu  lib
paragraph=
category=Communication
url=https://exploreembedded.com/wiki/AWS_IOT_with_Arduino_ESP32
architectures=*

# dot_a_linkage=true
#precompiled=true
